# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "auto_shops", :force => true do |t|
    t.column "name",          :string,                 :null => false
    t.column "num_customers", :integer, :default => 0, :null => false
    t.column "state_id",      :integer, :default => 0, :null => false
  end

  create_table "plugin_schema_info", :id => false, :force => true do |t|
    t.column "plugin_name", :string
    t.column "version",     :integer
  end

  create_table "switches", :force => true do |t|
    t.column "device",   :string,  :default => "light"
    t.column "state_id", :integer, :default => 0,       :null => false
  end

  create_table "vehicles", :force => true do |t|
    t.column "seatbelt_on",       :boolean, :default => true, :null => false
    t.column "insurance_premium", :integer, :default => 50,   :null => false
    t.column "type",              :string,                    :null => false
    t.column "state_id",          :integer, :default => 0,    :null => false
  end

end
